# Generated by Django 4.2.19 on 2025-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_founditem_user_lostitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_images/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_images/'),
        ),
    ]
